### ISSUE TITLE
p_min vprašanje:

### ISSUE THREAD

**Issue by sebastjan999** [sebastjan999/Touching-most-squares#1]
Pozdravljeni,

kot sva razumela Vaš gmail sva najino kodo in opis popravila in ju dopisala. Omenjenega p_min pa nisva definirala, zato naju zanima, če ga je sploh potrebno definirati, saj meniva, da so pogoji v drugem CLP programu ravno tako izpolnjeni brez njega. Za ekperimentiranje sva uvozila čas ter spremljala kako dolgo porabi algoritem za iskanje točke s CLP-jem, če se spreminja število kvadratov in velikost mreže. Misliva, da program deluje pravilno, zato bi Vas prosila za pregled kode in morebitne komentarje k kodi. 

Hvala za odgovor in lep pozdrav,
Sebastjan Šenk in Ana Marija Okorn

**Comment by jaanos** [comment]
Trenutno imata take omejitve:
```python
        p.add_constraint(p['k']*(x_i+1) + p['m'] + (1-u[i])*(p_max - y_min) >= y_i)
        p.add_constraint(p['k']*x_i + p['m'] - (1-u[i])*(p_max - y_min) <= y_i + 1)
```
V primeru, ko velja `u[i] == 0`, lahko drugo neenačbo zapišeta kot `(p['k']*x_i + p['m'] - p_max) + y_min <= y_i + 1` - ker vsota prvih dveh členov v oklepaju ne presega vrednosti `p_max`, je vrednost v oklepaju torej vedno manjša ali enaka 0, in ker velja `y_min <= y_i`, je neenakost vedno zadoščena. V nasprotju s tem pa pri prvi neenačbi tega ne moreta narediti - da bi dosegla želeno, bi bilo potrebno uporabiti `y_max` in `p_min` (da potem v primeru `u[i] == 0` velja `(p['k']*(x_i+1) + p['m'] - p_min) + y_max >= y_i`, kar je spet vedno res):
```python
        p.add_constraint(p['k']*(x_i+1) + p['m'] + (1-u[i])*(y_max - p_min) >= y_i)
```
Podobno seveda naredita še pri naslednji omejitvi (tipa `>=`).

Mimogrede, način, kako računata `p_max`, ni ustrezen - lahko se npr. zgodi, da sta dve točki zelo blizu po x, a zelo daleč po y, tako da je naklon skozi njiju zelo velik (ne glede na to, kako velik je `y_max`). Kot rečeno, bo treba obravnavati premice skozi pare oglišč vajinih kvadratov:
```python
oglisca = [(0, 0), (0, 1), (1, 0), (1, 1)]
seznam = []
for i, (x_i, y_i) in enumerate(seznam_tock): # izbira prvega kvadrata
    for x_j, y_j in seznam_tock[i+1:]: # izbira drugega kvadrata - brez ponovitev
        for w_i, z_i in oglisca: # izbira oglišča prvega kvadrata
            for w_j, z_j in oglisca: # izbira oglišča drugega kvadrata
                k = ((y_j+z_j) - (y_i+z_i)) / ((x_j+w_j) - (x_i+w_i))
                m = y_i+z_i - k * (x_i+w_i)
                for x in (x_min, x_max+1): # vrednosti x, kjer premica doseže največjo in najmanjšo vrednost y
                    seznam.append(k*x + m)
p_min, p_max = min(seznam), max(seznam)
```
Naj opozorim še, da je od predznaka `k` odvisno, pri katerem `x` bo premica dosegla največjo oziroma najmanjšo vrednost y.
